aliases - rename common file

diff --git a/aliases/bashrc_aliases b/aliases/bashrc_aliases
--- a/aliases/bashrc_aliases
+++ b/aliases/bashrc_aliases
@@ -1,13 +1,14 @@
-# regenerate common aliases
-$HOME/.aliases/gen_common_aliases.bash
+# Use following to regenerate common aliases
+#$HOME/.aliases/gen_common_aliases.bash
 
-aliasfile=$HOME/.common_aliases
+aliasfile=$HOME/.aliases/common_aliases
 if [ -f $aliasfile ]; then
-    tmpfile=$(mktemp --tmpdir aliases.bashtmp.$$.XXXXXX)
+    tmpfile=$(mktemp $TMPDIR/aliases.bashtmp.$$.XXXXXX)
+    [[ -f $tmpfile ]] || { echo "ERROR: mktemp failed"; exit 1; }
     
     fgrep ALIASTO $aliasfile | awk -F' ALIASTO ' '! /ARGV/ {printf("alias %s=%s\n",$1,$2)}' > $tmpfile
     fgrep ALIASTO $aliasfile | awk -F' ALIASTO ' '/ARGV/ {printf("%s() { %s ; }\n",$1,substr($2,2,length($2)-2))}' | sed -e 's/ARGV/\$\@/' >> $tmpfile
-    sed -e 's/SHELLEXT/sh/' $tmpfile > ${tmpfile}.sh
+    sed -e 's/SHELLEXT/bash/' $tmpfile > ${tmpfile}.sh
     # UNCOMMENT FOLLOWING TO DEBUG:
     #echo "==== alias tmpfile : ${tmpfile}.sh ===="
     #cat ${tmpfile}.sh
